### ISSUE TITLE
🚧Update workflow label for all repos

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/.github#27]
Go through all of the repositories and update the `workflow` label text to be `cicd` instead.

**Reason:**
This is because `workflow` started to be only for updating workflow files but it is a **CICD** type of thing.  Currently there is no label for other _**CICD**_ related work that does not deal directly with workflow files.  Changing this label's text means it could be used for anything CICD.

> **Note** Updating the text of a label automatically updates all of the labels for the issues.  No issue updating required.

**Acceptance Criteria:**
- [x] `workflow` label text changed to `cicd` for all repos.
    > **Note** Change the label text to **_CI/CD related work only_**
    - [x] GotNuget
    - [x] CASL
    - [x] VersionMiner
    - [x] Velaptor
    - [x] VersionValidator
    - [x] CICD
    - [x] Carbonate
    - [x] ScorpionEngine
    - [x] ParticleMaker
    - [x] ParticleEngine
    - [x] BranchValidator
    - [x] TagVerifier
    - [x] GitHubReleaseChecker
    - [x] IssueScanner

**Comment by kselena** [comment]
Created the PR before knowing it didn't need one.  Issue complete and moved to Done.
